### ISSUE TITLE
A fully functional lib to play video+audio 

### ISSUE THREAD

**Issue by bfred-it** [wewearglasses/InlineVideo#1]
I made one recently, I thought you'd be interested: https://github.com/bfred-it/iphone-inline-video

**Comment by wewearglasses** [comment]
That's a better solution. I didn't know you can grab the sound of video. 
What should we do next? Should I delete my branch?

**Comment by bfred-it** [comment]
No need to delete it, but you can add deprecation message + link to that, sort of like I did here: https://github.com/bfred-it-obsolete/build-url-query
